name: build
on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    if: (!startsWith(github.event.head_commit.message, 'chore(release):'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Get node version
        id: node
        run: echo "##[set-output name=VERSION;]$(cat .nvmrc)"
      - name: Set up node
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{steps.node.outputs.VERSION}}
      - name: Install packages
        run: npm i
      - name: Run tests
        run: npm test
      - name: Report coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{github.token}}
      - name: Run build
        run: npm run build
      - name: Release
        if: >
          github.ref == 'refs/heads/main' &&
          (
            github.event_name == 'schedule' ||
            (
              github.event_name == 'push' &&
              startsWith(github.event.head_commit.message, 'fix')
            )
          )
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{github.token}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
