name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    if: (!startsWith(github.event.head_commit.message, 'chore(release):'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get node version
        id: node
        run: echo "##[set-output name=VERSION;]$(cat .nvmrc)"
      - name: Setup node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{steps.node.outputs.VERSION}}
      - name: Install packages
        run: npm i
      - name: Run tests
        run: npm test
      - name: Report coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{github.token}}
      - name: Run build
        run: npm run build
      - name: Release
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.SEMANTIC_RELEASE_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
