name: build
on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    if: >
      !startsWith(github.event.head_commit.message, 'chore(release):') && !(
        github.event_name == 'push' &&
        startsWith(github.event.head_commit.message, 'chore(license):')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get node version
        id: node
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - name: Set up node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{steps.node.outputs.version}}
      - name: Set up cache
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: '**/node_modules'
          key: npm-${{hashFiles('**/package-lock.json')}}
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Report coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{github.token}}
      - name: Run build
        run: npm run build
      - name: Release
        if: >
          github.ref == 'refs/heads/main' && (
            github.event_name == 'schedule' || (
              github.event_name == 'push' && (
                startsWith(github.event.head_commit.message, 'fix') ||
                startsWith(github.event.head_commit.message, 'Revert')
              )
            )
          )
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.SEMANTIC_RELEASE_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
