name: Push
on:
  push:
    branches: main
concurrency: push
jobs:
  ci:
    name: CI
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/ci.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    needs:
     - ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - name: Set up node
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
