name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/sync-labels.yml
      - .github/labels.yml
jobs:
  sync-labels:
    name: sync-labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
