name: update-license
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-license.yml
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  update-license:
    name: update-license
    runs-on: ubuntu-latest
    env:
      BRANCH: auto/update-license
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Update license
        run: |
          sed -i -E "s/^(Copyright.*)[0-9]{4}(.*)$/\1$(date +%Y)\2/" LICENSE
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code LICENSE || echo "::set-output name=exist::true"
      - name: Push commit
        if: steps.changes.outputs.exist
        run: |
          git config user.name github-actions[bot]
          EMAIL=41898282+github-actions[bot]@users.noreply.github.com
          git config user.email $EMAIL
          git add LICENSE
          git commit -m "chore(license): update year to $(date +%Y)"
          git push
